### ISSUE TITLE
训练数据集格式似乎和stable diffusion官方数据集格式不符合，能给出dataset的格式或者要求吗

### ISSUE THREAD

**Issue by UncleshoesXR** [py85252876/Reconstruction-based-Attack#1]

**Comment by UncleshoesXR** [comment]
我使用了官方的mscoco和wit数据集，似乎都无法工作

**Comment by py85252876** [comment]
Each dataset file is a dictionary with two keys: `['image']` and `['text']`. The data at corresponding positions for these two keys is matched.

```plaintext
Dataset File
+-------------------+-------------------+
|      'image'      |      'text'       |
+-------------------+-------------------+
| Image 1           | Text 1            |
+-------------------+-------------------+
| Image 2           | Text 2            |
+-------------------+-------------------+
| Image 3           | Text 3            |
+-------------------+-------------------+
| ...               | ...               |
+-------------------+-------------------+
| Image N           | Text N            |
+-------------------+-------------------+

**Comment by UncleshoesXR** [comment]
> Each dataset file is a dictionary with two keys: `['image']` and `['text']`. The data at corresponding positions for these two keys is matched.
> 
> ```
> Dataset File
> +-------------------+-------------------+
> |      'image'      |      'text'       |
> +-------------------+-------------------+
> | Image 1           | Text 1            |
> +-------------------+-------------------+
> | Image 2           | Text 2            |
> +-------------------+-------------------+
> | Image 3           | Text 3            |
> +-------------------+-------------------+
> | ...               | ...               |
> +-------------------+-------------------+
> | Image N           | Text N            |
> +-------------------+-------------------+
> ```

thank you very much
